import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {Activity,ArrowLeft,ArrowUpRight,ChevronRight,Focus,Info,Layers3,LocateFixed,Moon,Pause,RotateCcw,RotateCw,Search,Sun,X,ZoomIn,ZoomOut} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import AnatomyScene from './scene';
import {buildIndex,highlight,searchConcepts,tokenize,type QueryToken} from './search';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,localizeAtlas,type Atlas,type Concept,type SceneState,type SystemId,type Theme,type View} from './anatomy';
const VIEW_LABELS:Record<View,string>={'three-quarter':'Вигляд у три чверті',front:'Вигляд спереду',side:'Вигляд збоку',back:'Вигляд ззаду'};
function plural(n:number,one:string,few:string,many:string){const m10=n%10,m100=n%100;return m10===1&&m100!==11?one:m10>=2&&m10<=4&&(m100<12||m100>14)?few:many;}
const POPULAR=['heart','brain','liver','stomach','spleen','pancreas','kidney','lung','urinary bladder','trachea','femur','skull'];
const PAGE=60;
function Marked({name,tokens}:{name:string;tokens:QueryToken[]}){return <>{highlight(name,tokens).map((p,i)=>p.hit?<mark key={i}>{p.text}</mark>:<span key={i}>{p.text}</span>)}</>;}
function storedTheme():Theme{try{const t=localStorage.getItem('atlas-theme');if(t==='light'||t==='dark')return t;}catch{/* storage may be blocked */}return typeof matchMedia!=='undefined'&&matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';}
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null),[history,setHistory]=useState<Concept[]>([]),[filterSystem,setFilterSystem]=useState<SystemId|null>(null),[limit,setLimit]=useState(PAGE),[cursor,setCursor]=useState(0);
 const searchInput=useRef<HTMLInputElement>(null),resultList=useRef<HTMLDivElement>(null);
 const [theme,setTheme]=useState<Theme>(storedTheme),[zoom,setZoom]=useState({id:0,factor:1}),[focus,setFocus]=useState(0);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.querySelector('meta[name=theme-color]')?.setAttribute('content',theme==='dark'?'#0f1419':'#f3f4f4');try{localStorage.setItem('atlas-theme',theme);}catch{/* storage may be blocked */}},[theme]);
 const zoomBy=(factor:number)=>setZoom(z=>({id:z.id+1,factor}));
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});const load=(url:string)=>fetch(url,{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('Не вдалося завантажити анатомічний каталог.');return r.json();});Promise.all([load('models/atlas.json'),load('models/names-uk.json'),load('models/names-la.json')]).then(([data,uk,la])=>setAtlas(localizeAtlas(data as Atlas,uk as Record<string,string>,la as Record<string,string>))).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}if(e.key==='Escape')setPanel(p=>p==='search'?null:p);if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.ctrlKey||e.metaKey)return;if(e.key==='+'||e.key==='=')zoomBy(.75);else if(e.key==='-'||e.key==='_')zoomBy(1/.75);else if(e.key==='f'||e.key==='а')setFocus(f=>f+1);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const index=useMemo(()=>atlas?buildIndex(atlas.concepts):[],[atlas]);
 /** A concept belongs to the system that most of its pieces belong to. */
 const conceptSystem=useMemo(()=>{const m=new Map<string,SystemId>();for(const c of atlas?.concepts??[]){const tally=new Map<SystemId,number>();for(const id of c.elements){const p=parts.get(id);if(p)tally.set(p.system,(tally.get(p.system)??0)+1);}const best=[...tally].sort((a,b)=>b[1]-a[1])[0];if(best)m.set(c.id,best[0]);}return m;},[atlas,parts]);
 const conceptsByPart=useMemo(()=>{const m=new Map<string,Concept[]>();for(const c of atlas?.concepts??[])for(const id of c.elements){const list=m.get(id);if(list)list.push(c);else m.set(id,[c]);}return m;},[atlas]);
 const tokens=useMemo(()=>tokenize(query),[query]);
 const results=useMemo(()=>{if(!atlas)return[];const inSystem=filterSystem?(c:Concept)=>conceptSystem.get(c.id)===filterSystem:undefined;if(tokens.length)return searchConcepts(index,query,inSystem);if(inSystem)return atlas.concepts.filter(inSystem).sort((a,b)=>a.name.localeCompare(b.name,'uk'));return POPULAR.map(name=>atlas.concepts.find(c=>(c.nameEn??c.name).toLowerCase()===name)).filter((x):x is Concept=>!!x);},[atlas,index,query,tokens,filterSystem,conceptSystem]);
 useEffect(()=>{setLimit(PAGE);setCursor(0);},[query,filterSystem]);
 const shown=results.slice(0,limit);
 /** The smallest named structures that contain everything currently selected. */
 const parents=useMemo(()=>{if(!chosen||!state.selected.length)return[];const first=conceptsByPart.get(state.selected[0])??[];return first.filter(c=>c.id!==chosen.id&&c.elements.length>state.selected.length&&state.selected.every(id=>c.elements.includes(id))).sort((a,b)=>a.elements.length-b.elements.length).slice(0,6);},[chosen,state.selected,conceptsByPart]);
 const remember=()=>{if(chosen&&details)setHistory(h=>[...h.slice(-19),chosen]);};
 const choose=(c:Concept)=>{remember();setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const back=()=>{const prev=history[history.length-1];if(!prev)return;setHistory(h=>h.slice(0,-1));setChosen(prev);setState(s=>({...s,selected:prev.elements,isolate:false,rotate:false}));setDetails(true);};
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;remember();setChosen(atlas?.concepts.find(c=>c.id===p.conceptId&&c.elements.length===1&&c.elements[0]===id)??{id:p.conceptId,name:p.name,nameEn:p.nameEn,nameLa:p.nameLa,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setHistory([]);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0,theme,zoom,focus}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> ІНТЕРАКТИВНА АНАТОМІЯ</div><h1>Атлас людини<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString('uk'):'2 234'} змодельованих елементів <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label="Панелі атласу"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Пошук у атласі"><Search size={18}/><span>Знайти структуру</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label={theme==='dark'?'Світла тема':'Темна тема'} title={theme==='dark'?'Світла тема':'Темна тема'} onClick={()=>setTheme(t=>t==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</Button><Button variant="ghost" className="icon-button" aria-label="Про атлас" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Анатомічні шари">
   <div className="panel-heading"><span>Системи</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Закрити системи"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>Усі</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>Скелет</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>Органи</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Показати лише: ${s.name.toLocaleLowerCase('uk')}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Показати: ${s.name.toLocaleLowerCase('uk')}`} /></div>)}</div>
   <div className="panel-foot"><span>Видимих елементів: {visibleCount.toLocaleString('uk')}</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Приховати всі</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Пошук структур">
   <div className="panel-heading"><span>Знайти структуру</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Закрити пошук"><X size={18}/></Button></div>
   <div className="search-field"><Search size={16}/><input ref={searchInput} autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Слова з назви: ліва нирка, femur, arteria…" aria-label="Пошук анатомічних структур за назвою" aria-controls="search-results" aria-activedescendant={shown[cursor]?`result-${shown[cursor].id}`:undefined} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setCursor(c=>Math.min(c+1,shown.length-1));}else if(e.key==='ArrowUp'){e.preventDefault();setCursor(c=>Math.max(c-1,0));}else if(e.key==='Enter'&&shown[cursor]){e.preventDefault();choose(shown[cursor]);}}}/>{query&&<button className="search-clear" onClick={()=>{setQuery('');searchInput.current?.focus();}} aria-label="Очистити пошук"><X size={14}/></button>}</div>
   <div className="system-filter" role="group" aria-label="Фільтр за системою"><button aria-pressed={!filterSystem} onClick={()=>setFilterSystem(null)}>Усі системи</button>{activeSystems.map(s=><button key={s.id} aria-pressed={filterSystem===s.id} onClick={()=>setFilterSystem(f=>f===s.id?null:s.id)}><i style={{background:s.color}}/>{s.name}</button>)}</div>
   <div className="search-summary">{tokens.length?(results.length?`Знайдено ${results.length.toLocaleString('uk')} ${plural(results.length,'структуру','структури','структур')}`:'Нічого не знайдено'):filterSystem?`${SYSTEMS.find(x=>x.id===filterSystem)?.name}: ${results.length.toLocaleString('uk')} ${plural(results.length,'структура','структури','структур')} за абеткою`:'Популярні органи'}</div>
   <div className="search-results" id="search-results" role="listbox" ref={resultList}>{shown.map((c,i)=><button role="option" aria-selected={i===cursor} id={`result-${c.id}`} key={c.id} style={{'--i':Math.min(i%PAGE,14)} as CSSProperties} className={i===cursor?'current':''} onMouseEnter={()=>setCursor(i)} onClick={()=>choose(c)}><span className="result-text"><span className="result-name"><Marked name={c.name} tokens={tokens}/></span>{c.nameLa&&<span className="result-latin"><Marked name={c.nameLa} tokens={tokens}/></span>}</span><span className="result-meta">{conceptSystem.get(c.id)&&<i style={{background:SYSTEMS.find(x=>x.id===conceptSystem.get(c.id))?.color}}/>}{c.elements.length}</span></button>)}{results.length>shown.length&&<button className="show-more" onClick={()=>setLimit(l=>l+PAGE)}>Показати ще ({(results.length-shown.length).toLocaleString('uk')})</button>}{tokens.length>0&&!results.length&&<p className="search-empty">Спробуйте коротше слово або іншу мову: пошук працює українською, латиною та англійською, слова можна писати в будь-якому порядку.</p>}</div>
  </section>}
  <nav className="view-controls glass" aria-label="Керування камерою">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={VIEW_LABELS[v]} aria-label={VIEW_LABELS[v]}><span>{['¾','П','Б','З'][i]}</span></Button>)}<i/><Button variant="ghost" aria-label="Наблизити" title="Наблизити (+)" onClick={()=>zoomBy(.75)}><ZoomIn size={18}/></Button><Button variant="ghost" aria-label="Віддалити" title="Віддалити (−)" onClick={()=>zoomBy(1/.75)}><ZoomOut size={18}/></Button><Button variant="ghost" aria-label="Наблизити до вибраної структури" title="До вибраної структури (F)" disabled={!state.selected.length} onClick={()=>setFocus(f=>f+1)}><LocateFixed size={18}/></Button><i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Зупинити обертання':'Обертати тіло'} title="Автообертання" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Скинути вигляд і шари" title="Скинути" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name.toLocaleUpperCase('uk')??'ВИБРАНА СТРУКТУРА'):state.explode>.95?'АНАТОМІЧНИЙ ПЕРЕЛІК':state.explode>.05?'РОЗДІЛЕНІ СТРУКТУРИ':'ДОРОСЛА ЛЮДИНА · ЧОЛОВІК'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Відкрити шари систем"><Layers3 size={20}/><span>Системи</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Розібрати анатомію</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Зібрано</span><span>Кожен елемент</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Зібрати й скинути"><RotateCcw size={18}/><span>Скинути</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Перетягніть, щоб зсунути':'Перетягніть, щоб обертати'} <b>·</b> Колесо або +/− — масштаб <b>·</b> Клік — оглянути <b>·</b> F — до вибраного <b>·</b> / — пошук</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Джерела й авторство <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Готуємо анатомічну модель</strong><span>{progress}% · Завантаження {atlas?.parts.length.toLocaleString('uk')??'2 234'} елементів</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Перезавантажити</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header">{history.length>0&&<button className="detail-back" onClick={back}><ArrowLeft size={14}/>Назад до «{history[history.length-1].name}»</button>}<div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name.toLocaleUpperCase('uk')??'АНАТОМІЯ'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle>{chosen?.nameLa&&<p className="structure-latin" lang="la">{chosen.nameLa}</p>}</div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.nameEn??chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[(chosen.nameEn??chosen.name).toLowerCase()]&&<span className="context-note">Огляд системи · структуру визначено за вихідною анатомічною моделлю</span>}<div className="structure-meta"><span>Система<strong>{system?.name??'—'}</strong></span><span>Елементів моделі<strong>{state.selected.length.toLocaleString('uk')}</strong></span></div>{chosen?.nameEn&&<div className="source-name">Англійською: <span lang="en">{chosen.nameEn}</span></div>}{parents.length>0&&<div className="member-list"><h3>Входить до складу</h3>{parents.map(c=><Button variant="ghost" key={c.id} onClick={()=>choose(c)}><span>{c.name}</span><ChevronRight size={14}/></Button>)}</div>}{selectedParts.length>1&&<div className="member-list"><h3>Складові частини</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>І ще {selectedParts.length-50} {plural(selectedParts.length-50,'змодельований елемент','змодельовані елементи','змодельованих елементів')}.</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">Переглянути анатомічне джерело <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button variant="ghost" className="focus-action" onClick={()=>setFocus(f=>f+1)}><LocateFixed size={16}/>Наблизити на моделі</Button><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Показати навколишні структури':'Ізолювати структуру'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Скасувати вибір</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">ДЖЕРЕЛО Й ОХОПЛЕННЯ</div><SheetTitle className="structure-title">Тіло людини в 3D</SheetTitle><SheetDescription>Референсна анатомія дорослого чоловіка з бази BodyParts3D.</SheetDescription><div className="about-copy"><p><strong>Чоловік · BodyParts3D</strong><br/>2 234 окремі 3D-моделі та 3 432 названі анатомічні поняття з референсної анатомії дорослого чоловіка.</p><p>Модель не охоплює всіх структур тіла людини та їхніх варіантів. Одне назване поняття може складатися з кількох елементів; кожна вихідна модель відображається один раз.</p><p>Кольори та групування за системами підібрано для зручного вивчення. Геометрію спрощено для вебу, а короткі пояснення дають загальний навчальний контекст. Атлас є довідковим ресурсом і не призначений для діагностики чи планування операцій.</p><h3>Український переклад</h3><p>Назви структур перекладено українською відповідно до анатомічної термінології та доповнено латинськими назвами за Міжнародною анатомічною термінологією. Оригінальні англійські назви BodyParts3D збережено. Шукати можна будь-якою з трьох мов.</p><h3>Як користуватися</h3><p>Натисніть «/» або кнопку пошуку й введіть кілька слів із назви в будь-якому порядку, наприклад «нирка ліва» чи «arteria renalis». Фільтр за системою під полем пошуку показує всі структури системи за абеткою. У картці структури можна перейти до частин, з яких вона складається, або до більшої структури, до якої вона входить, і повернутися кнопкою «Назад».</p><h3>Джерело</h3><p>BodyParts3D, © The Database Center for Life Science, ліцензія CC Attribution 4.0 International.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Ліцензія набору даних <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">Оригінальна геометрія та метадані <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">Публікація про джерело даних <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
