import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,localizeAtlas,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const VIEW_LABELS:Record<View,string>={'three-quarter':'Вигляд у три чверті',front:'Вигляд спереду',side:'Вигляд збоку',back:'Вигляд ззаду'};
function plural(n:number,one:string,few:string,many:string){const m10=n%10,m100=n%100;return m10===1&&m100!==11?one:m10>=2&&m10<=4&&(m100<12||m100>14)?few:many;}
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});const load=(url:string)=>fetch(url,{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('Не вдалося завантажити анатомічний каталог.');return r.json();});Promise.all([load('/models/atlas.json'),load('/models/names-uk.json')]).then(([data,names])=>setAtlas(localizeAtlas(data as Atlas,names as Record<string,string>))).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLocaleLowerCase('uk').trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>(c.nameEn??c.name).toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLocaleLowerCase('uk').includes(term)||(c.nameEn??'').toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,nameEn:p.nameEn,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> ІНТЕРАКТИВНА АНАТОМІЯ</div><h1>Атлас людини<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString('uk'):'2 234'} змодельованих елементів <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label="Панелі атласу"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Пошук у атласі"><Search size={18}/><span>Знайти структуру</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="Про атлас" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Анатомічні шари">
   <div className="panel-heading"><span>Системи</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Закрити системи"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>Усі</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>Скелет</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>Органи</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Показати лише: ${s.name.toLocaleLowerCase('uk')}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Показати: ${s.name.toLocaleLowerCase('uk')}`} /></div>)}</div>
   <div className="panel-foot"><span>Видимих елементів: {visibleCount.toLocaleString('uk')}</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Приховати всі</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Пошук структур"><div className="panel-heading"><span>Знайти структуру</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Закрити пошук"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Серце, стегнова кістка, femur…" aria-label="Пошук анатомічних структур за назвою" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>За вашим запитом структур не знайдено.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {plural(c.elements.length,'елемент','елементи','елементів')}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Показано до 80 збігів. Уточніть запит, щоб знайти дрібніші структури. Пошук працює українською та англійською.':'Почніть із великого органа або шукайте будь-яку названу структуру українською чи англійською.'}</p></section>}
  <nav className="view-controls glass" aria-label="Керування камерою">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={VIEW_LABELS[v]} aria-label={VIEW_LABELS[v]}><span>{['¾','П','Б','З'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Зупинити обертання':'Обертати тіло'} title="Автообертання" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Скинути вигляд і шари" title="Скинути" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name.toLocaleUpperCase('uk')??'ВИБРАНА СТРУКТУРА'):state.explode>.95?'АНАТОМІЧНИЙ ПЕРЕЛІК':state.explode>.05?'РОЗДІЛЕНІ СТРУКТУРИ':'ДОРОСЛА ЛЮДИНА · ЧОЛОВІК'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Відкрити шари систем"><Layers3 size={20}/><span>Системи</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Розібрати анатомію</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Зібрано</span><span>Кожен елемент</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Зібрати й скинути"><RotateCcw size={18}/><span>Скинути</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Перетягніть, щоб зсунути':'Перетягніть, щоб обертати'} <b>·</b> Зведіть пальці, щоб масштабувати <b>·</b> Торкніться, щоб оглянути</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Джерела й авторство <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Готуємо анатомічну модель</strong><span>{progress}% · Завантаження {atlas?.parts.length.toLocaleString('uk')??'2 234'} елементів</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Перезавантажити</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name.toLocaleUpperCase('uk')??'АНАТОМІЯ'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.nameEn??chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[(chosen.nameEn??chosen.name).toLowerCase()]&&<span className="context-note">Огляд системи · структуру визначено за вихідною анатомічною моделлю</span>}<div className="structure-meta"><span>Ідентифікатор<strong>{chosen?.id}</strong></span><span>Вибрано елементів<strong>{state.selected.length.toLocaleString('uk')}</strong></span></div>{chosen?.nameEn&&<div className="source-name">Назва в BodyParts3D: <span>{chosen.nameEn}</span></div>}{selectedParts.length>1&&<div className="member-list"><h3>Складові структури</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>І ще {selectedParts.length-50} {plural(selectedParts.length-50,'змодельований елемент','змодельовані елементи','змодельованих елементів')}.</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">Переглянути анатомічне джерело <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Показати навколишні структури':'Ізолювати структуру'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Скасувати вибір</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">ДЖЕРЕЛО Й ОХОПЛЕННЯ</div><SheetTitle className="structure-title">Тіло людини в 3D</SheetTitle><SheetDescription>Референсна анатомія дорослого чоловіка з бази BodyParts3D.</SheetDescription><div className="about-copy"><p><strong>Чоловік · BodyParts3D</strong><br/>2 234 окремі 3D-моделі та 3 432 названі анатомічні поняття з референсної анатомії дорослого чоловіка.</p><p>Модель не охоплює всіх структур тіла людини та їхніх варіантів. Одне назване поняття може складатися з кількох елементів; кожна вихідна модель відображається один раз.</p><p>Кольори та групування за системами підібрано для зручного вивчення. Геометрію спрощено для вебу, а короткі пояснення дають загальний навчальний контекст. Атлас є довідковим ресурсом і не призначений для діагностики чи планування операцій.</p><h3>Український переклад</h3><p>Назви структур перекладено українською відповідно до анатомічної термінології. Оригінальні англійські назви BodyParts3D збережено: за ними теж можна шукати, і вони показані в картці структури.</p><h3>Джерело</h3><p>BodyParts3D, © The Database Center for Life Science, ліцензія CC Attribution 4.0 International.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Ліцензія набору даних <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">Оригінальна геометрія та метадані <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">Публікація про джерело даних <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
